---
name: 'Test'

on:
  pull_request: {}
  push:
    branches: ['master']

permissions:
  contents: 'read'

jobs:
  all:
    name: 'Unit Test'
    needs: 'test'
    if: 'always()'
    runs-on: 'ubuntu-latest'
    steps:
      - if: "needs.test.result != 'success'"
        run: 'exit 1'

  test:
    name: '${{ matrix.project }}'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        project:
          - 'corpus'
          - 'fast'
    steps:
      - uses: 'actions/checkout@v7'
        with:
          lfs: true

      - name: 'Install dependencies'
        run: 'sudo apt-get update && sudo apt-get install --no-install-recommends --yes tesseract-ocr tesseract-ocr-eng'

      - uses: 'pnpm/setup@v3'
        with:
          cache: true
      - run: 'pnpm vitest run --project ${{ matrix.project }}'
